services:
  db-dev:
    image: postgres:latest
    container_name: db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hongdat10
      POSTGRES_DB: blog-dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres-dev

networks:
  postgres-dev:
    driver: bridge

volumes:
  postgres_data_dev:
    driver: local
